import { createFileRoute } from "@tanstack/react-router";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { CarCard } from "@/components/car-card";
import { DiscoveryFilters, type FleetFilter } from "@/components/discovery-filters";
import { useLanguage } from "@/lib/language";
import { cars } from "@/lib/site-data";
export const Route=createFileRoute("/fleet")({head:()=>({meta:[{title:"Luxury Car Fleet Dubai — ARDADAGCI"},{name:"description",content:"Entdecken Sie Luxusautos, Sportwagen, Cabrios und SUVs zur Miete in Dubai."},{property:"og:title",content:"Luxury Car Fleet Dubai — ARDADAGCI"},{property:"og:description",content:"Luxusfahrzeuge in Dubai ohne Kaution reservieren."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:FleetPage});
function FleetPage(){const {language}=useLanguage();const [filter,setFilter]=useState<FleetFilter>({type:"all",value:""});const [query,setQuery]=useState("");const shown=useMemo(()=>cars.filter(car=>(filter.type==="all"||(filter.type==="brand"?car.brand===filter.value:car.category===filter.value))&&`${car.brand} ${car.name}`.toLowerCase().includes(query.toLowerCase())),[filter,query]);return <><section className="fleet-intro site-shell"><p>{language==="de"?"Luxus-Autovermietung Dubai":"Luxury car rental Dubai"}</p><div><h1>{language==="de"?"Finden Sie Ihr Fahrzeug":"Find your car"}</h1><label className="fleet-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={language==="de"?"Marke oder Modell":"Brand or model"} aria-label={language==="de"?"Flotte durchsuchen":"Search fleet"}/></label></div></section><section className="site-shell"><DiscoveryFilters active={filter} onChange={setFilter}/></section><section className="site-shell fleet-page-grid"><div className="section-title"><h2>{language==="de"?"Verfügbare Fahrzeuge":"Available cars"}</h2><span>{shown.length} {language==="de"?"Fahrzeuge":"cars"}</span></div><div className="fleet-grid">{shown.map(car=><CarCard key={car.slug} car={car}/>)}</div></section></>}
