import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, Gauge, MessageCircle, ShieldCheck, Timer, Users, Workflow } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CarCard } from "@/components/car-card";
import { useLanguage } from "@/lib/language";
import { cars, whatsappUrl } from "@/lib/site-data";
export const Route=createFileRoute("/fleet/$slug")({loader:({params})=>{const car=cars.find(c=>c.slug===params.slug);if(!car)throw notFound();return {car}},head:({loaderData})=>({meta:[{title:loaderData?`${loaderData.car.brand} ${loaderData.car.name} Rental Dubai — ARDADAGCI`:"Vehicle unavailable — ARDADAGCI"},{name:"description",content:loaderData?`Rent the ${loaderData.car.brand} ${loaderData.car.name} in Dubai from AED ${loaderData.car.price.toLocaleString("en-US")} per day.`:"Vehicle unavailable."},{property:"og:title",content:loaderData?`${loaderData.car.brand} ${loaderData.car.name} — ARDADAGCI`:"Vehicle unavailable"},{property:"og:description",content:loaderData?.car.description??"Explore the ARDADAGCI fleet."},{property:"og:type",content:"product"},{name:"twitter:card",content:"summary_large_image"}]}),component:CarPage});
function CarPage(){const {language}=useLanguage();const {car}=Route.useLoaderData();const related=cars.filter(c=>c.slug!==car.slug).slice(0,3);return <><section className="site-shell vehicle-page"><Button asChild variant="ghost" className="back-link"><Link to="/fleet"><ArrowLeft/>{language==="de"?"Zur Flotte":"Back to fleet"}</Link></Button><div className="vehicle-layout"><div className="vehicle-image"><img src={car.image} alt={`${car.brand} ${car.name}`}/><span className="deposit-badge">{language==="de"?"0 € Kaution":"No Deposit"}</span></div><div className="vehicle-info"><p>{car.brand} · {car.category}</p><h1>{car.name}</h1><p>{car.description}</p><div className="vehicle-price"><span>{language==="de"?"Tagespreis":"Daily rate"}</span><strong>AED {car.price.toLocaleString("en-US")}</strong><span>/ {language==="de"?"Tag":"day"}</span></div><div className="vehicle-actions"><Button asChild size="xl"><a href={whatsappUrl(`${language==="de"?"Hallo, ich möchte":"Hello, I would like to book"} ${car.brand} ${car.name} ${language==="de"?"reservieren":""}.`)} target="_blank" rel="noreferrer"><MessageCircle/>{language==="de"?"WhatsApp Reservierung":"WhatsApp booking"}</a></Button><Button asChild size="xl" variant="outline"><Link to="/booking" search={{car:car.slug}}>{language==="de"?"Kontaktformular":"Contact form"}</Link></Button></div></div></div><div className="spec-grid"><Spec icon={Gauge} label={language==="de"?"Leistung":"Power"} value={car.hp}/><Spec icon={Timer} label="0–100 km/h" value={car.zeroToHundred}/><Spec icon={Workflow} label={language==="de"?"Getriebe":"Transmission"} value={car.transmission}/><Spec icon={Users} label={language==="de"?"Sitze":"Seats"} value={String(car.seats)}/></div><div className="perk-row"><span><ShieldCheck/>{language==="de"?"Keine Kaution":"No deposit"}</span><span><ShieldCheck/>{language==="de"?"Lieferung in Dubai":"Dubai delivery"}</span><span><ShieldCheck/>{language==="de"?"24/7 Support":"24/7 support"}</span></div></section><section className="site-shell related-cars"><h2>{language==="de"?"Weitere Fahrzeuge":"You may also like"}</h2><div className="fleet-grid">{related.map(c=><CarCard key={c.slug} car={c}/>)}</div></section></>}
function Spec({icon:Icon,label,value}:{icon:typeof Gauge;label:string;value:string}){return <div><Icon/><span>{label}</span><strong>{value}</strong></div>}
