/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as FleetSlugRouteImport } from './routes/fleet.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetSlugRoute = FleetSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FleetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/tiktok': typeof TiktokRoute
  '/fleet/$slug': typeof FleetSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/tiktok': typeof TiktokRoute
  '/fleet/$slug': typeof FleetSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/tiktok': typeof TiktokRoute
  '/fleet/$slug': typeof FleetSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/fleet'
    | '/reviews'
    | '/tiktok'
    | '/fleet/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/fleet'
    | '/reviews'
    | '/tiktok'
    | '/fleet/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/fleet'
    | '/reviews'
    | '/tiktok'
    | '/fleet/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  FleetRoute: typeof FleetRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  TiktokRoute: typeof TiktokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$slug': {
      id: '/fleet/$slug'
      path: '/$slug'
      fullPath: '/fleet/$slug'
      preLoaderRoute: typeof FleetSlugRouteImport
      parentRoute: typeof FleetRoute
    }
  }
}

interface FleetRouteChildren {
  FleetSlugRoute: typeof FleetSlugRoute
}

const FleetRouteChildren: FleetRouteChildren = {
  FleetSlugRoute: FleetSlugRoute,
}

const FleetRouteWithChildren = FleetRoute._addFileChildren(FleetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  FleetRoute: FleetRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  TiktokRoute: TiktokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
